create table customer (
                          id int primary key,
                          first_name varchar(100) not null,
                          last_name varchar(100) not null,
                          city varchar(100),
                          country varchar(100),
                          phone varchar(100)
);
insert into customer (id, first_name, last_name, city, country, phone) values (1, 'Redd', 'Wandless', 'Boljevci', 'Serbia', '642-485-2883');
insert into customer (id, first_name, last_name, city, country, phone) values (2, 'Winfred', 'Lettsom', 'Vilela', 'Portugal', '983-861-2634');
insert into customer (id, first_name, last_name, city, country, phone) values (3, 'Bertrando', 'Croci', 'Tongmuluo', 'China', '710-235-3859');
insert into customer (id, first_name, last_name, city, country, phone) values (4, 'Dall', 'Lynthal', 'Lipa City', 'Philippines', '399-597-0984');
insert into customer (id, first_name, last_name, city, country, phone) values (5, 'Wynnie', 'Warde', 'Vol’no-Nadezhdinskoye', 'Russia', '916-169-1063');
insert into customer (id, first_name, last_name, city, country, phone) values (6, 'Leonelle', 'Girk', 'Xinzhou', 'China', '126-897-1918');
insert into customer (id, first_name, last_name, city, country, phone) values (7, 'Angeli', 'Hurren', 'Ketapang', 'Indonesia', '173-633-2679');
insert into customer (id, first_name, last_name, city, country, phone) values (8, 'Carlin', 'Leeburne', 'Banatski Dvor', 'Serbia', '638-829-5463');
insert into customer (id, first_name, last_name, city, country, phone) values (9, 'Giulia', 'Schultz', 'San Antonio', 'Peru', '293-319-2421');
insert into customer (id, first_name, last_name, city, country, phone) values (10, 'Anna-diana', 'Zorzoni', 'Shakhta', 'Russia', '110-664-4410');
insert into customer (id, first_name, last_name, city, country, phone) values (11, 'Ernestus', 'Adamowitz', 'Mirovice', 'Czech Republic', '847-787-7062');
insert into customer (id, first_name, last_name, city, country, phone) values (12, 'Daryl', 'Piel', 'Rajsko', 'Poland', '883-644-8709');
insert into customer (id, first_name, last_name, city, country, phone) values (13, 'Melodee', 'Gordge', 'Huaquirca', 'Peru', '883-217-6575');
insert into customer (id, first_name, last_name, city, country, phone) values (14, 'Maurise', 'Tindley', 'Dagar', 'China', '296-999-5874');
insert into customer (id, first_name, last_name, city, country, phone) values (15, 'Irita', 'Woolston', 'Orissaare', 'Estonia', '806-864-1925');
insert into customer (id, first_name, last_name, city, country, phone) values (16, 'Tish', 'Tunnadine', 'Tála', 'Cyprus', '702-736-6384');
insert into customer (id, first_name, last_name, city, country, phone) values (17, 'Dewitt', 'Staite', 'Bradford', 'United Kingdom', '539-714-2966');
insert into customer (id, first_name, last_name, city, country, phone) values (18, 'Lisetta', 'Baversor', 'Falun', 'Sweden', '984-860-9223');
insert into customer (id, first_name, last_name, city, country, phone) values (19, 'Geoffrey', 'Nenci', 'Alquerubim', 'Portugal', '347-129-0824');
insert into customer (id, first_name, last_name, city, country, phone) values (20, 'Adelice', 'Duiguid', 'Kokoshkino', 'Russia', '913-542-1747');
insert into customer (id, first_name, last_name, city, country, phone) values (21, 'Willy', 'Traher', 'Portland', 'United States', '971-284-7878');
insert into customer (id, first_name, last_name, city, country, phone) values (22, 'Ingrid', 'Abbate', 'Xushangqiao', 'China', '642-396-3478');
insert into customer (id, first_name, last_name, city, country, phone) values (23, 'Berna', 'Ishchenko', 'Dzhubga', 'Russia', '170-375-7584');
insert into customer (id, first_name, last_name, city, country, phone) values (24, 'Nolie', 'Akroyd', 'Laocheng', 'China', '629-941-4296');
insert into customer (id, first_name, last_name, city, country, phone) values (25, 'Hayley', 'Magee', 'Dieppe', 'France', '853-603-2369');
insert into customer (id, first_name, last_name, city, country, phone) values (26, 'Wolfgang', 'Wagner', 'Datian', 'China', '675-824-2182');
insert into customer (id, first_name, last_name, city, country, phone) values (27, 'Dore', 'Gillise', 'Sa''dah', 'Yemen', '106-709-6701');
insert into customer (id, first_name, last_name, city, country, phone) values (28, 'Ilaire', 'Fleay', 'Martin', 'Croatia', '348-971-4256');
insert into customer (id, first_name, last_name, city, country, phone) values (29, 'Mikael', 'Tartt', 'Santa Magdalena', 'Philippines', '142-264-2340');
insert into customer (id, first_name, last_name, city, country, phone) values (30, 'Morgan', 'Pledger', 'Tessaoua', 'Niger', '202-769-1442');
insert into customer (id, first_name, last_name, city, country, phone) values (31, 'Anne-corinne', 'de Bullion', 'Tsotsin-Yurt', 'Russia', '127-536-3150');
insert into customer (id, first_name, last_name, city, country, phone) values (32, 'Barrett', 'Pursglove', 'Liudong', 'China', '532-943-5187');
insert into customer (id, first_name, last_name, city, country, phone) values (33, 'Delano', 'Lotterington', 'Sharan', 'Russia', '925-772-5916');
insert into customer (id, first_name, last_name, city, country, phone) values (34, 'Ban', 'Coley', 'Menol', 'Indonesia', '916-110-5322');
insert into customer (id, first_name, last_name, city, country, phone) values (35, 'Mozes', 'Haffner', 'Jiangluo', 'China', '936-260-4258');
insert into customer (id, first_name, last_name, city, country, phone) values (36, 'Burk', 'Darlow', 'Lingmen', 'China', '205-732-5717');
insert into customer (id, first_name, last_name, city, country, phone) values (37, 'Stillmann', 'Antyshev', 'Pravda', 'Russia', '756-675-4229');
insert into customer (id, first_name, last_name, city, country, phone) values (38, 'Harwell', 'Caldicott', 'Ferraz de Vasconcelos', 'Brazil', '665-197-2228');
insert into customer (id, first_name, last_name, city, country, phone) values (39, 'Kristy', 'Cottesford', 'Longtan', 'China', '218-629-0000');
insert into customer (id, first_name, last_name, city, country, phone) values (40, 'Merv', 'Macia', 'Kryevidh', 'Albania', '383-538-5890');
insert into customer (id, first_name, last_name, city, country, phone) values (41, 'Urson', 'Klimov', 'Brumadinho', 'Brazil', '306-342-1336');
insert into customer (id, first_name, last_name, city, country, phone) values (42, 'Nels', 'Jessopp', 'Brongkah', 'Indonesia', '209-689-6062');
insert into customer (id, first_name, last_name, city, country, phone) values (43, 'Vivienne', 'Crasswell', 'Talpe', 'Sri Lanka', '469-759-1689');
insert into customer (id, first_name, last_name, city, country, phone) values (44, 'Cybill', 'Bernaldo', 'At Tāj', 'Libya', '556-462-9238');
insert into customer (id, first_name, last_name, city, country, phone) values (45, 'Immanuel', 'Buckler', 'Toronto', 'Canada', '664-297-3757');
insert into customer (id, first_name, last_name, city, country, phone) values (46, 'Meggy', 'Drynan', 'Xihuaiba', 'China', '549-555-6841');
insert into customer (id, first_name, last_name, city, country, phone) values (47, 'Morie', 'Uman', 'Payao', 'Philippines', '298-457-1354');
insert into customer (id, first_name, last_name, city, country, phone) values (48, 'Fraze', 'MacMickan', 'Kayapa', 'Philippines', '721-858-6942');
insert into customer (id, first_name, last_name, city, country, phone) values (49, 'Tremayne', 'Terzi', 'Balta', 'Ukraine', '547-268-9380');
insert into customer (id, first_name, last_name, city, country, phone) values (50, 'Leonie', 'Sail', 'Banzão', 'Portugal', '571-425-8977');
insert into customer (id, first_name, last_name, city, country, phone) values (51, 'Anallise', 'Michallat', 'Joaquín V. González', 'Argentina', '713-397-1838');
insert into customer (id, first_name, last_name, city, country, phone) values (52, 'Paten', 'Ragbourn', 'Ermelo', 'South Africa', '282-727-2870');
insert into customer (id, first_name, last_name, city, country, phone) values (53, 'Godiva', 'Wickmann', 'San Vicente', 'Philippines', '191-453-2220');
insert into customer (id, first_name, last_name, city, country, phone) values (54, 'Ariana', 'Checchetelli', 'Murcia', 'Philippines', '309-243-0611');
insert into customer (id, first_name, last_name, city, country, phone) values (55, 'Jesse', 'Greenard', 'Taipingxu', 'China', '883-408-1866');
insert into customer (id, first_name, last_name, city, country, phone) values (56, 'Isabeau', 'Gravatt', 'Surin', 'Thailand', '499-466-0175');
insert into customer (id, first_name, last_name, city, country, phone) values (57, 'Drud', 'Surpliss', 'Cilampuyang', 'Indonesia', '873-736-5082');
insert into customer (id, first_name, last_name, city, country, phone) values (58, 'Benn', 'Breyt', 'Banyubang', 'Indonesia', '109-645-2824');
insert into customer (id, first_name, last_name, city, country, phone) values (59, 'Jessika', 'McPike', 'Bayt Adhāqah', 'Yemen', '508-577-9231');
insert into customer (id, first_name, last_name, city, country, phone) values (60, 'Hamlen', 'Turone', 'Ajaccio', 'France', '335-756-4630');
insert into customer (id, first_name, last_name, city, country, phone) values (61, 'Tiena', 'Avrahamoff', 'Zmiennica', 'Poland', '259-909-8536');
insert into customer (id, first_name, last_name, city, country, phone) values (62, 'Seymour', 'O''Cleary', 'Agoo', 'Philippines', '158-604-5942');
insert into customer (id, first_name, last_name, city, country, phone) values (63, 'Meier', 'McAlister', 'Serzedo', 'Portugal', '273-441-4411');
insert into customer (id, first_name, last_name, city, country, phone) values (64, 'Dwayne', 'Busst', 'Honolulu', 'United States', '808-563-9144');
insert into customer (id, first_name, last_name, city, country, phone) values (65, 'Carlynn', 'Gilbanks', 'Kristianstad', 'Sweden', '554-411-7485');
insert into customer (id, first_name, last_name, city, country, phone) values (66, 'Dyana', 'Rubinovici', 'Yahil’nytsya', 'Ukraine', '191-582-1709');
insert into customer (id, first_name, last_name, city, country, phone) values (67, 'Cahra', 'MacAne', 'Iturama', 'Brazil', '577-361-2268');
insert into customer (id, first_name, last_name, city, country, phone) values (68, 'Kristel', 'Oleszkiewicz', 'Muang Phôn-Hông', 'Laos', '225-651-8427');
insert into customer (id, first_name, last_name, city, country, phone) values (69, 'Jaimie', 'Dansken', 'Pu’an', 'China', '669-404-9721');
insert into customer (id, first_name, last_name, city, country, phone) values (70, 'Dominic', 'Cisec', 'Mananjary', 'Madagascar', '217-375-1329');
insert into customer (id, first_name, last_name, city, country, phone) values (71, 'Josie', 'Kitchingham', 'Kabasalan', 'Philippines', '387-515-0474');
insert into customer (id, first_name, last_name, city, country, phone) values (72, 'Harlie', 'Dearl', 'Shiojiri', 'Japan', '906-404-1842');
insert into customer (id, first_name, last_name, city, country, phone) values (73, 'Alexa', 'Mc Corley', 'Gueset', 'Philippines', '453-490-5713');
insert into customer (id, first_name, last_name, city, country, phone) values (74, 'Zilvia', 'Dickman', 'Huating', 'China', '966-891-9076');
insert into customer (id, first_name, last_name, city, country, phone) values (75, 'Yard', 'Baglan', 'Youxi', 'China', '816-474-6135');
insert into customer (id, first_name, last_name, city, country, phone) values (76, 'Heather', 'Buzin', 'Bigaan', 'Philippines', '853-113-4559');
insert into customer (id, first_name, last_name, city, country, phone) values (77, 'Veda', 'Giacomelli', 'Angus', 'Canada', '692-356-4322');
insert into customer (id, first_name, last_name, city, country, phone) values (78, 'Cathleen', 'Cornes', 'Mempawah', 'Indonesia', '370-654-2668');
insert into customer (id, first_name, last_name, city, country, phone) values (79, 'Andrei', 'Klaus', 'Winton', 'New Zealand', '582-763-2564');
insert into customer (id, first_name, last_name, city, country, phone) values (80, 'Effie', 'Jerke', 'Nanfeng', 'China', '820-122-3650');
insert into customer (id, first_name, last_name, city, country, phone) values (81, 'Lynett', 'Tossell', 'Mbala', 'Zambia', '739-464-0225');
insert into customer (id, first_name, last_name, city, country, phone) values (82, 'Leeann', 'Beatens', 'La Libertad', 'Philippines', '272-222-0256');
insert into customer (id, first_name, last_name, city, country, phone) values (83, 'Durand', 'Scanderet', 'Mandalay', 'Myanmar', '263-600-1469');
insert into customer (id, first_name, last_name, city, country, phone) values (84, 'Carol-jean', 'Digby', 'Beaumont', 'Ireland', '681-700-2322');
insert into customer (id, first_name, last_name, city, country, phone) values (85, 'Ivy', 'Altoft', 'Los Andes', 'Chile', '262-757-0492');
insert into customer (id, first_name, last_name, city, country, phone) values (86, 'Niles', 'Savins', 'Zlynka', 'Ukraine', '731-182-2225');
insert into customer (id, first_name, last_name, city, country, phone) values (87, 'Cece', 'Fryman', 'Arari', 'Brazil', '359-685-7448');
insert into customer (id, first_name, last_name, city, country, phone) values (88, 'Livvyy', 'Greeson', 'Chiţcani', 'Moldova', '447-638-4202');
insert into customer (id, first_name, last_name, city, country, phone) values (89, 'Stacie', 'Bondley', 'La Puerta de San José', 'Argentina', '920-550-4185');
insert into customer (id, first_name, last_name, city, country, phone) values (90, 'Kaye', 'Marklow', 'Tinaco', 'Venezuela', '471-785-6133');
insert into customer (id, first_name, last_name, city, country, phone) values (91, 'Rod', 'St. Hill', 'Saposoa', 'Peru', '728-471-4940');
insert into customer (id, first_name, last_name, city, country, phone) values (92, 'Alaster', 'Dilleston', 'Kalamangog', 'Philippines', '134-609-5815');
insert into customer (id, first_name, last_name, city, country, phone) values (93, 'Vance', 'Tunuy', 'Cabrero', 'Chile', '384-577-2882');
insert into customer (id, first_name, last_name, city, country, phone) values (94, 'Ado', 'Glayzer', 'Tando Jām', 'Pakistan', '485-417-5473');
insert into customer (id, first_name, last_name, city, country, phone) values (95, 'Dorothea', 'Jerrams', 'Chignayhua', 'Peru', '520-517-3684');
insert into customer (id, first_name, last_name, city, country, phone) values (96, 'Yetty', 'Blasdale', 'Béziers', 'France', '406-800-9989');
insert into customer (id, first_name, last_name, city, country, phone) values (97, 'Emmey', 'Plaister', 'Phan Thong', 'Thailand', '659-127-7189');
insert into customer (id, first_name, last_name, city, country, phone) values (98, 'Elvin', 'Towll', 'Padangguci', 'Indonesia', '448-381-5066');
insert into customer (id, first_name, last_name, city, country, phone) values (99, 'Wylie', 'Balsom', 'Sukkozero', 'Russia', '159-466-1513');
insert into customer (id, first_name, last_name, city, country, phone) values (100, 'Allys', 'Issacov', 'Zhongcheng', 'China', '496-536-6510');
